name: Auto Rebase PRs on main update

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
